app:
  name: rollerskatestelemetry
  labels: rollerskatestelemetry
  replicas: 1
  port: 8080
  restartPolicy: Always
  type: LoadBalancer

zookeeper:
  name: zookeeper
  labels: zookeeper
  replicas: 1
  port: 2181
  restartPolicy: Always
  type: LoadBalancer

kafka:
  name: kafka
  labels: kafka
  replicas: 1
  advertised_host_name: kafka
  topics: topic1:1:1
  port: 9092
  restartPolicy: Always
  type: LoadBalancer

postgres:
  name: postgres
  labels:  postgres
  replicas: 1
  postgres_db: roller_skates_telemetry
  TZ: Europe/Moscow
  port: 5432
  restartPolicy: Always
  type: LoadBalancer
