version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=roller_skates_telemetry
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1"
  rollerskatestelemetry:
    image: rollerskatestelemetry:v1
    container_name: rollerskatestelemetry
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/roller_skates_telemetry?serverTimezone=Europe/Moscow
    depends_on:
      - db
      - zookeeper
      - kafka



