apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.labels }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgres_db }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: name
            - name: TZ
              value: {{ .Values.postgres.TZ }}
          image: postgres:latest
          name: postgres
          ports:
            - containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      restartPolicy: {{ .Values.postgres.restartPolicy }}
      volumes:
        - name: init-script
          configMap:
            name: init-script
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgres.labels }}
  name: {{ .Values.postgres.name }}
spec:
  ports:
    - name: "port"
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.name }}
  type: {{ .Values.postgres.type }}

