apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.labels }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels }}
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://{{ .Values.postgres.name }}:{{ .Values.postgres.port }}/{{ .Values.postgres.postgres_db }}?serverTimezone={{ .Values.postgres.TZ }}
        - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
          value: {{ .Values.kafka.name }}:{{ .Values.kafka.port }}
        image: rollerskatestelemetry:v1
        name: rollerskatestelemetry
        ports:
        - containerPort: {{ .Values.app.port }}
      restartPolicy: {{ .Values.app.restartPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ .Values.app.labels }}
  name: {{ .Values.app.name }}
spec:
  ports:
    - name: "port"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.type }}
